In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data type: int64


In [2]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
identity = np.eye(3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity matrix:\n", identity)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
arr = np.arange(10, 51, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [5]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [6]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [7]:
arr = np.array([2, 3, 4, 5])

print("Square:", arr ** 2)
print("Cube:", arr ** 3)

Square: [ 4  9 16 25]
Cube: [  8  27  64 125]


In [8]:
arr = np.array([100, 200, 300, 400])

result = arr * 1.15
print(result)

[115. 230. 345. 460.]


In [9]:
a = np.array([10, 40, 20, 60])
b = np.array([30, 20, 50, 40])

print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [30 40 50 60]
Minimum: [10 20 20 40]


In [10]:
arr = np.arange(21)

print("First five:", arr[:5])
print("Last five:", arr[-5:])
print("Index 5 to 15:", arr[5:16])
print("Every second element:", arr[::2])

First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]


In [11]:
arr = np.arange(10)
arr[:5] = 100

print(arr)

[100 100 100 100 100   5   6   7   8   9]


In [12]:
arr = np.array([10, 20, 30, 40, 50])

view = arr[1:4]
view[0] = 999

print("Original after modifying view:", arr)

copy = arr[1:4].copy()
copy[0] = 888

print("Original after modifying copy:", arr)
print("Copy:", copy)

Original after modifying view: [ 10 999  30  40  50]
Original after modifying copy: [ 10 999  30  40  50]
Copy: [888  30  40]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[::-1])

[50 40 30 20 10]


In [14]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Second row:", arr[1, :])
print("Third column:", arr[:, 2])
print("Element 50:", arr[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [15]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

sub = arr[0:2, 1:3]
print(sub)

[[20 30]
 [50 60]]


In [16]:
arr = np.arange(1, 26).reshape(5, 5)

print("Matrix:\n", arr)
print("First row:", arr[0, :])
print("Last column:", arr[:, -1])
print("Middle element:", arr[2, 2])
print("Top-left 3x3:\n", arr[:3, :3])

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13
Top-left 3x3:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [17]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr = np.arange(1, 11)
result = arr.reshape(2, 5)

print(result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
arr = np.arange(1, 13).reshape(3, 4)

print("Original:\n", arr)
print("Transpose:\n", arr.T)

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [20]:
arr = np.arange(1, 13).reshape(2, 2, 3)

print("Original:\n", arr)
print("Transpose:\n", arr.transpose(1, 0, 2))
print("Swap axes:\n", np.swapaxes(arr, 0, 2))

Original:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Transpose:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
Swap axes:
 [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [21]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Addition:\n", A + B)
print("Element-wise multiplication:\n", A * B)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [23]:
A = np.array([[1, 2], [3, 4]])

AT = A.T
result = np.dot(AT, A)

print("Transpose:\n", AT)
print("Dot product:\n", result)

Transpose:
 [[1 3]
 [2 4]]
Dot product:
 [[10 14]
 [14 20]]


In [24]:
arr = np.array([4, 9, 16, 25, 36])

print(np.sqrt(arr))

[2. 3. 4. 5. 6.]


In [25]:
arr = np.array([0, 1, 2, 3])

print(np.exp(arr))

[ 1.          2.71828183  7.3890561  20.08553692]


In [26]:
arr = np.array([1.0, -2.0, 3.0, -4.0])

print("Square root:", np.sqrt(np.abs(arr)))
print("Exponential:", np.exp(arr))
print("Absolute values:", np.abs(arr))

Square root: [1.         1.41421356 1.73205081 2.        ]
Exponential: [2.71828183e+00 1.35335283e-01 2.00855369e+01 1.83156389e-02]
Absolute values: [1. 2. 3. 4.]


In [27]:
A = np.random.randint(1, 20, size=5)
B = np.random.randint(1, 20, size=5)

print("A:", A)
print("B:", B)
print("Maximum:", np.maximum(A, B))

A: [10 19 15 12 12]
B: [ 7 15 13 19 13]
Maximum: [10 19 15 19 13]


In [28]:
marks = np.array([35, 72, 48, 90, 55, 28])

result = np.where(marks < 40, 0, marks)
print(result)

[ 0 72 48 90 55  0]


In [29]:
income = np.array([25000, 60000, 45000, 80000, 50000])

category = np.where(income >= 50000, "High", "Low")
print(category)

['Low' 'High' 'Low' 'High' 'High']


In [30]:
arr = np.array([10, 25, 35, 40, 15, 50])

result = np.where(arr > 30, 100, arr)
print(result)

[ 10  25 100 100  15 100]


In [31]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

Sum: 45
Mean: 5.0


In [32]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Row sums:", np.sum(arr, axis=1))
print("Column sums:", np.sum(arr, axis=0))

Row sums: [ 6 15 24]
Column sums: [12 15 18]


In [33]:
import numpy as np

marks = np.array([65, 78, 82, 45, 90, 56, 72, 88, 61, 95])

print("Mean:", np.mean(marks))
print("Standard deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Mean: 73.2
Standard deviation: 15.445387661046258
Minimum: 45
Maximum: 95


In [34]:
import numpy as np

arr = np.array([True, True, False])

print("Any:", np.any(arr))
print("All:", np.all(arr))

Any: True
All: False


In [35]:
import numpy as np

arr = np.random.randint(1, 100, 10)

print("Random numbers:", arr)
print("Sorted numbers:", np.sort(arr))

Random numbers: [57 99 48 15 21 60 37 85 69 62]
Sorted numbers: [15 21 37 48 57 60 62 69 85 99]


In [36]:
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5, 5])

print("Unique elements:", np.unique(arr))

Unique elements: [1 2 3 4 5]


In [37]:
import numpy as np

marks = np.array([75, 80, 75, 90, 80, 65, 90, 85])

print("Unique marks:", np.unique(marks))

Unique marks: [65 75 80 85 90]


In [38]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
values = np.array([20, 40, 60])

print(np.isin(values, arr))

[ True  True False]


In [39]:
import numpy as np

marks = np.array([
    [70, 80, 90],
    [40, 50, 60],
    [30, 35, 40],
    [85, 90, 95],
    [55, 60, 65],
    [20, 25, 30],
    [75, 70, 80],
    [45, 50, 40],
    [90, 85, 88],
    [60, 65, 70]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)

print("Total:", total)
print("Average:", average)
print("Qualified students:", np.where(average >= 50)[0] + 1)

Total: [240 150 105 270 180  75 225 135 263 195]
Average: [80.         50.         35.         90.         60.         25.
 75.         45.         87.66666667 65.        ]
Qualified students: [ 1  2  4  5  7  9 10]


In [40]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

print("Matrix:\n", arr)
print("Transpose:\n", arr.T)
print("Row sums:", np.sum(arr, axis=1))
print("Column sums:", np.sum(arr, axis=0))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Central 2x2:\n", arr[1:3, 1:3])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row sums: [10 26 42 58]
Column sums: [28 32 36 40]
Mean: 8.5
Maximum: 16
Minimum: 1
Central 2x2:
 [[ 6  7]
 [10 11]]


In [41]:
import numpy as np

arr = np.random.randn(20)

print("Observations:", arr)
print("Mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Sorted:", np.sort(arr))

result = np.where(arr < 0, 0, arr)
print("Negative values replaced:", result)

Observations: [ 0.92684897  1.06372704  1.31025545  0.08342631  0.5731238  -1.51357329
 -2.11493946 -0.32897739 -0.12824739 -2.63218311  1.31877629  0.91252383
  0.15632155 -0.89836251 -1.06705441 -0.55604632  0.038688    0.31399742
  0.3228517   0.05331504]
Mean: -0.10827642433692378
Standard deviation: 1.0649775801050911
Minimum: -2.63218311368405
Maximum: 1.3187762891021853
Sorted: [-2.63218311 -2.11493946 -1.51357329 -1.06705441 -0.89836251 -0.55604632
 -0.32897739 -0.12824739  0.038688    0.05331504  0.08342631  0.15632155
  0.31399742  0.3228517   0.5731238   0.91252383  0.92684897  1.06372704
  1.31025545  1.31877629]
Negative values replaced: [0.92684897 1.06372704 1.31025545 0.08342631 0.5731238  0.
 0.         0.         0.         0.         1.31877629 0.91252383
 0.15632155 0.         0.         0.         0.038688   0.31399742
 0.3228517  0.05331504]


In [42]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition = A + B
element_multiplication = A * B
matrix_multiplication = np.dot(A, B)

print("Addition:\n", addition)
print("Element multiplication:\n", element_multiplication)
print("Matrix multiplication:\n", matrix_multiplication)
print("Transpose of A:\n", A.T)
print("Maximum:", np.max(matrix_multiplication))
print("Minimum:", np.min(matrix_multiplication))

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Element multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Maximum: 138
Minimum: 18


In [43]:
import numpy as np

arr = np.arange(1, 25).reshape(4, 6)

print("Original matrix:\n", arr)
print("First row:", arr[0, :])
print("Last two rows:\n", arr[2:4, :])
print("Second column:", arr[:, 1])
print("Columns 2 to 4:\n", arr[:, 1:4])
print("Transpose:\n", arr.T)

print("Row sums:", np.sum(arr, axis=1))
print("Column sums:", np.sum(arr, axis=0))
print("Row means:", np.mean(arr, axis=1))
print("Column means:", np.mean(arr, axis=0))
print("Unique values:", np.unique(arr))

Original matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
First row: [1 2 3 4 5 6]
Last two rows:
 [[13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Second column: [ 2  8 14 20]
Columns 2 to 4:
 [[ 2  3  4]
 [ 8  9 10]
 [14 15 16]
 [20 21 22]]
Transpose:
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]
Row sums: [ 21  57  93 129]
Column sums: [40 44 48 52 56 60]
Row means: [ 3.5  9.5 15.5 21.5]
Column means: [10. 11. 12. 13. 14. 15.]
Unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
